steps:

# Run unit tests and code coverage
- name: 'python:3.6-slim-jessie'
  entrypoint: 'bash'
  dir: 'tests'
  args: ['run_tests.sh']
  id: 'Tests'

# compile pipeline
- name: 'python:3.7'
  entrypoint: 'bash'
  dir: 'pipeline'
  args: ['pipeline_builder.sh', '${_PIPELINE_PATH}']
  #waitFor: ['Tests']
  id: 'CompilePipeline'

# run pipeline
- name: 'python:3.7'
  entrypoint: 'bash'
  dir: 'pipeline'
  args: ['pipeline_runner.sh', '${_PIPELINE_PATH}', '${_LOCATION}', '${_PIPELINE_PARAMS}', '${_PIPELINE_NAME}', '${_PROJECT_ID}', '${_PIPELINE_ROOT}', '${_PIPELINE_RUN_NAME}']
  waitFor: ['CompilePipeline']
  id: 'RunPipeline'

substitutions:
  _PIPELINE_ROOT: gs://$REPO_NAME/$SHORT_SHA
  _PIPELINE_PATH: gs://$REPO_NAME/$SHORT_SHA/pipeline.json
  _LOCATION: us-central1
  _PIPELINE_NAME: my-test
  _PIPELINE_RUN_NAME: $SHORT_SHA
  _PROJECT_ID: $PROJECT_ID
  _PIPELINE_PARAMS: "'{\"project_id\": \"feature-store-mars21\",   \"data_path\": \"gs://mortgage_dataset_files/mortgage-small.csv\"}'"