steps:

# Run unit tests and code coverage
- name: 'python:3.6-slim-jessie'
  entrypoint: 'bash'
  dir: 'tests'
  args: ['run_tests.sh']
  id: 'Tests'

# compile pipeline
- name: 'python:3.7'
  entrypoint: 'bash'
  dir: 'pipelines'
  args: ['pipeline_builder.sh', '${_PIPELINE_PATH}', 'deploy_model']
  waitFor: ['Tests']
  id: 'CompilePipeline'

# run pipeline
- name: 'python:3.7'
  entrypoint: 'bash'
  dir: 'pipelines'
  args: ['pipeline_runner.sh', '${_PIPELINE_PATH}', '${_LOCATION}', '${_PIPELINE_PARAMS}', '${_PIPELINE_NAME}', '${_PROJECT_ID}', '${_PIPELINE_ROOT}', '${_PIPELINE_RUN_NAME}', '${_SERVICE_ACCOUNT}']
  waitFor: ['CompilePipeline']
  id: 'RunPipeline'
  timeout: 1800s



substitutions:
  _PIPELINE_ROOT: "gs://${PROJECT_ID}/${REPO_NAME}"
  _PIPELINE_PATH: "gs://${PROJECT_ID}/${REPO_NAME}/deploy_model_pipeline.json"
  _SERVICE_ACCOUNT: "pipelines-cloud-build@feature-store-mars21.iam.gserviceaccount.com"
  _LOCATION: us-central1
  _PIPELINE_NAME: ${REPO_NAME}
  _PIPELINE_RUN_NAME: build-dm-${REPO_NAME}-${SHORT_SHA}
  _PROJECT_ID: ${PROJECT_ID}
  _PIPELINE_PARAMS: "{\"project_id\":\"${PROJECT_ID}\",\"region\":\"us-central1\",\"metadata_name\":\"default\",\"model_uri_path\":\"gs://${PROJECT_ID}/${REPO_NAME}\",\"endpoint_name\":\"test-deploy-ep\"}"